### ISSUE TITLE
Support angular 5+?

### ISSUE THREAD

**Issue by shajeeck** [ZouYouShun/ngx-y2-player#1]
Hello is there any way i can get this working in angular 5+? since i am using ionic 3 which is currently based on "@angular/common":"5.2.11" and "rxjs": "5.5.11"

Any help will be appreciated.

**Comment by ZouYouShun** [comment]
Hi @shajeeck, this latest version is not support 5.x now, because I use the angular 6+ service Injectable way : ```provideIn:'root'```
```js
@Injectable({
  providedIn: 'root'
})
```
If you can't upgrade your project, you can use the old version ``` npm i ngx-y2-player@1.1.0``` [@1.1.0](https://www.npmjs.com/package/ngx-y2-player/v/1.1.0).
