### ISSUE TITLE
updated to 3.0.0.  i'm getting the following build errors (screenshot). Angular 8.1.2

### ISSUE THREAD

**Issue by collabcoders** [ZouYouShun/ngx-y2-player#10]
<img width="1191" alt="Screen Shot 2019-08-19 at 9 09 45 PM" src="https://user-images.githubusercontent.com/6439938/63317060-3cbf6480-c2c6-11e9-989c-1b8580fcfd06.png">

**Comment by ZouYouShun** [comment]
oh, I forget the "dependencies" with "@types/youtube", I fix that with 3.0.1.

you can try that with `npm i ngx-y2-player@3.0.1`

**Comment by ZouYouShun** [comment]
Hi @collabcoders, is there any problem with 3.0.1, if not I'll close this issue.
