### ISSUE TITLE
Angular 7 Update

### ISSUE THREAD

**Issue by SebastianRuecker** [ZouYouShun/ngx-y2-player#2]
Could this be updated for angular 7?
```
npm WARN ngx-y2-player@1.4.0 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-y2-player@1.4.0 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by ZouYouShun** [comment]
Hi @SebastianRuecker, I has upgrade this peer dependancies to more than 6.0.0, you can install it with `npm i ngx-y2-player@1.4.1`.

thanks for your reminder.

**Comment by SebastianRuecker** [comment]
Hi @ZouYouShun, thank you for your fast response. but I think there is a little error at your commit...
i receive follwing warning `npm WARN ngx-y2-player@1.4.1 requires a peer of @angular/core@^>=6.0.0 but none is installed. You must install peer dependencies yourself.`

i think your peerDependencies had to be like this (without **^** in front of >=6.0.0 @ angular/core)
```
"peerDependencies": {
    "@angular/common": ">=6.0.0",
    "@angular/core": ">=6.0.0"
}
```

**Comment by ZouYouShun** [comment]
oh! I make a mistake with that....

I think I am tired 😂😂😂

thank you!
