### ISSUE TITLE
Support to GDPR

### ISSUE THREAD

**Issue by kalicki** [ZouYouShun/ngx-y2-player#4]
Add support to `host` (GDPR)

Ref:
https://portalzine.de/dev/api/youtube-iframe-api-and-cookieless-domain-solution-gdpr-dsgvo/
https://stackoverflow.com/questions/46161026/is-it-possible-to-disable-cookies-for-youtube-api-iframe-player

**Comment by ZouYouShun** [comment]
I add the host with 2.0.0.

more detial in https://alanzouhome.firebaseapp.com/package/NgxY2Player

https://github.com/ZouYouShun/ngx-y2-player/blob/master/CHANGELOG..md

**Comment by kalicki** [comment]
100% works!
