### ISSUE TITLE
Error getPlayerState is not function

### ISSUE THREAD

**Issue by kalicki** [ZouYouShun/ngx-y2-player#5]
Hey,

```
<ngx-y2-player #video class="video-player" [videoId]="media" [playerOptions]="playerOptions" (ready)="playerReady()"
        (stateChange)="playerChange($event)">
      </ngx-y2-player>
```

```
// simple example
ngOnInit() {
    // http get
    ...service.getByID(ID).subscribe(data => {
      // Populate vídeo
      this.media = data.steps[0].media;
    });
}
```

![screen shot 2019-03-07 at 17 14 35](https://user-images.githubusercontent.com/3674885/53986321-9fe48280-40fc-11e9-8b89-84245549b4e3.png)

**Comment by kalicki** [comment]
up?

**Comment by ZouYouShun** [comment]
Hi @kalicki , you need using that in our custom event `(ready)="onReady($event)"`, the youtube API need element binding when the element exist, so must use that AfterViewInit and the player will get the youtube API async, so only get the veidePlayer in our custom event.

Example:
https://stackblitz.com/edit/ngx-y2-player-example-ready

**Comment by kalicki** [comment]
@ZouYouShun Now I use `ionViewWillEnter` and `[videoId]= "stepMedia"` to populate video, but the big question is that I do not want to capture the player, I'm just running `playVideo`

```
  ionViewWillEnter() {
    stepMedia = 'xasdaosk'
  }

  toggleModePlayer() {
    setTimeout(() => {
      !this.isPlaying ? this.video.videoPlayer.playVideo() : this.video.videoPlayer.pauseVideo();
    }, 100);
  }

  playerReady(event) {
    this.toggleModePlayer();
  }
```

**Comment by ZouYouShun** [comment]
I can't understand your problem

If you using playerReady to trigger toggleModePlayer, that doesn't need timeout at all.

the player exists at that moment.

Are you want to switch videoId and set the same state with the previous state?

**Comment by kalicki** [comment]
![Screen Shot 2019-04-10 at 11 47 22](https://user-images.githubusercontent.com/3674885/55888877-8bc1f400-5b86-11e9-996f-7c6b7275962e.png)

Good question...
the problem seems in syncronized of how the thing should happen, because this error does not always appear, sometimes yes and sometimes not
