### ISSUE TITLE
Blocked by "Adblock plus" content

### ISSUE THREAD

**Issue by vidhyasgr** [ZouYouShun/ngx-y2-player#6]
I get an error if it try to play any video. It is blocked by extension.

Do you have any solution for that?

**Comment by ZouYouShun** [comment]
Hi @vidhyasgr,  
What error that you meet? could you give me some error message?

**Comment by vidhyasgr** [comment]
Hi @ZouYouShun thanks for your response! Actually if you make the iframe display none, then its not playing google chrome. 

It does not say anthing in console.

**Comment by ZouYouShun** [comment]
you can't set display none with youtube player, that check in the youtube player API.
