### ISSUE TITLE
NgxY2PlayerOptions.width can be string too ("100%")

### ISSUE THREAD

**Issue by AmirSavand** [ZouYouShun/ngx-y2-player#7]
The value can be `'100%'` but the type is set to `number` or `'auto'` only.

**Comment by ZouYouShun** [comment]
> The value can be `'100%'` but the type is set to `number` or `'auto'` only.

Hey! @AmirSavand  we using auto resize to make player resize automatically, you should use the `[container]` and a wrapper with our player, to make that resize automatically.

https://stackblitz.com/edit/ngx-y2-player-example-ready
