### ISSUE TITLE
iframeElement, videoPlay missing on first load with clean cache

### ISSUE THREAD

**Issue by gentlemanjohn** [ZouYouShun/ngx-y2-player#8]
Angular 7.2.0
ngx-y2-player 2.1.1

Video won't play on initial page load but works fine in subsequent page loads.  When I clear cache I face the same problem.  The error message is:

`ERROR TypeError: Cannot read property 'playVideo' of undefined`

Sure enough when I inspect NgxY2PlayerComponent, I see that iframeElement and playVideo are missing on the first page load.

**Comment by ZouYouShun** [comment]
Hi @gentlemanjohn, where are you call that playVideo method?

I think that using that in error life cycle, make sure you use that after our custom `(ready)` method.

https://github.com/ZouYouShun/ngx-y2-player#attribute
