### ISSUE TITLE
Not working in Angular 8.1.2

### ISSUE THREAD

**Issue by collabcoders** [ZouYouShun/ngx-y2-player#9]
This package hasn't been updated in a while.  WIll support for angular 8 be coming?

**Comment by ZouYouShun** [comment]
oh! @collabcoders, sorry about so late to see this issue, I will fix that today.

**Comment by ZouYouShun** [comment]
@collabcoders  I have been updated the package to angular v8, you can try that with
 `npm install ngx-y2-player@3.0.0`
